controller_manager:
  ros__parameters:
    update_rate: 10 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_group_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints: 
      - joint1
      - joint2
      - joint3
    interface_name: position
    goal_tolerance: 0.01
    allow_partial_joint_goal: true    # 允许仅指定部分关节发送指令

gpio_controller:
  ros__parameters:
    type: gpio_controllers/GpioCommandController
    gpios:
      - gpio_test
    command_interfaces:
      gpio_estop:
        - interfaces:
          - emstop_input
    state_interfaces:
      gpio_estop:
        - interfaces:
          - emstop_output


