controller_manager:
  ros__parameters:
    update_rate: 10 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gpio_controller:
      type: gpio_controllers/GpioCommandController

arm_group_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    constraints: 0.02
    allow_partial_joints_goal: true
    open_loop_control: true

gpio_controller:
  ros__parameters:
    gpios:
      - gpio_test
    command_interfaces:
      gpio_test:
        - interfaces:
          - emstop_input
    state_interfaces:
      gpio_test:
        - interfaces:
          - emstop_output

